### PR TITLE
Add community forum button and fix margin and spacing issues with header

### PR DESCRIPTION
**Pull request by TomWFox**
I have added a new button for the community forum as there is no existing link to the new forum.

I have also improved the margins on various header elements so that the header looks more pleasing and legible on desktop but in particular mobile.

I have attached two GIFs of the before and after respectively:

**Before:**
before changes

**After:**
after changes

### CODE REVIEW

**Comment by awgeorge** [comment]
If we're not keeping Gitter, there is always: https://github.com/parse-community/parse-community.github.io/pull/15

**Comment by TomWFox** [comment]
@awgeorge It seems that the Gitter chat is still fairly active so maybe it should be kept for now?

**Comment by awgeorge** [comment]
Depends on what the plan is, I do think it would be a good idea to consolidate the number of support channels, as people wouldn't know where to go first. If the Gitter chat would be better suited as a threaded chat forum, I would try and focus the effort on a single platform. - just IMO

**Comment by TomWFox** [comment]
I agree, I’ve never used the Gitter chat as it always seems to much of a pain.

Maybe you should close your PR now so we’re not doubling up? - I only suggest that as I have made other improvements to the header and can easily remove the Gitter button if needed.

**Review by acinader — APPROVED** [review]

**Review by acinader — APPROVED** [review]

**Comment by TomWFox** [comment]
I’m not sure as to whether I should have made the changes in the main.scss file instead #16 does that.

**Pull request merged**
